theme = "catppuccin_mocha"

[editor]
auto-save = true
auto-format = true
# auto-pairs = false
cursorline = true
# cursorcolumn = true
line-number = "relative"
mouse = false
bufferline = "multiple"
completion-trigger-len = 1
idle-timeout = 0

[editor.lsp]
display-inlay-hints = true
display-messages = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.indent-guides]
render = true

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
